apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
  labels:
    name: docker-app-service
    app: demo-docker-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: docker-app-pod
    app: demo-docker-app